### ISSUE TITLE
Important

### ISSUE THREAD

**Issue by Ridhubharan** [Antiru/First-go-to#4]
> Hey man lets go out

**Comment by Antiru** [comment]
Really!!!!!!!! Comon man its intresting i am getting NOTHING

**Comment by Ridhubharan** [comment]
WTF!!!!

**Comment by Antiru** [comment]
Its not WTF its Where the Fuck i am???

**Comment by Ridhubharan** [comment]
Common man , there are no girls near me , I'm getting bored

**Comment by Antiru** [comment]
Be a man and learn to survive without girls

**Comment by Ridhubharan** [comment]
Then , Fuck yourself

**Comment by Ridhubharan** [comment]
Yo man lets go out

**Comment by Antiru** [comment]
.!.

**Comment by Antiru** [comment]
(.)(.)

**Comment by Ridhubharan** [comment]
I'm going , bye bye
